server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/goserver?serverTimezone=UTC
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USER}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml